language: objective-c
xcode_workspace: XLCUtils.xcworkspace
before_install:
      - gem install cocoapods --no-rdoc --no-ri --no-document --quiet 
      - pod repo update
      - brew update
      - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
matrix:
    include:
        - xcode_sdk: macosx
          xcode_scheme: XLCUtils
        - xcode_sdk: iphonesimulator
          xcode_scheme: XLCUtils-ios
