language: objective-c
xcode_workspace: XLCUtils.xcworkspace
before_install:
      - gem install cocoapods
      - pod repo update --verbose
      - brew update
      - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
matrix:
    include:
        - xcode_sdk: macosx
          xcode_scheme: XLCUtils
        - xcode_sdk: iphonesimulator
          xcode_scheme: XLCUtils-ios
